# Generated by Django 4.2.16 on 2025-07-21 17:22

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='机巢名称')),
                ('model', models.CharField(default='', max_length=50, verbose_name='机巢型号')),
                ('nest_sn', models.CharField(max_length=50, unique=True, verbose_name='机巢SN')),
                ('plane_model', models.CharField(default='', max_length=50, verbose_name='飞机型号')),
                ('plane_sn', models.CharField(max_length=50, verbose_name='飞机SN')),
                ('location', models.CharField(default='', max_length=255, verbose_name='机巢位置')),
                ('organization', models.CharField(default='', max_length=255, verbose_name='所属单位')),
                ('longitude', models.FloatField(default=0, verbose_name='机巢经度')),
                ('latitude', models.FloatField(default=0, verbose_name='机巢纬度')),
                ('status', models.IntegerField(default=1, verbose_name='机巢状态')),
                ('owner', models.CharField(default='', max_length=100, verbose_name='维护人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机巢信息',
                'verbose_name_plural': '机巢信息',
                'db_table': 's_nest',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_id', models.IntegerField(default=1, verbose_name='菜单')),
                ('role_id', models.IntegerField(default=1, verbose_name='角色')),
            ],
            options={
                'db_table': 's_role_menu',
            },
        ),
        migrations.CreateModel(
            name='SysDictData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='字典标签')),
                ('value', models.CharField(default='', max_length=500, verbose_name='字典键值')),
                ('sort', models.IntegerField(verbose_name='字典排序')),
                ('dict_type', models.CharField(default='', max_length=100, verbose_name='字典类型')),
                ('create_by', models.CharField(default='', max_length=50, verbose_name='创建者')),
                ('status', models.IntegerField(default=1, verbose_name='标签状态(1正常，0停用)')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remark', models.CharField(default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'db_table': 's_dict_data',
            },
        ),
        migrations.CreateModel(
            name='SysDictType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cn_name', models.CharField(default='', max_length=50, unique=True, verbose_name='字典中文名称')),
                ('en_name', models.CharField(default='', max_length=50, verbose_name='字典英文名称')),
                ('status', models.IntegerField(default=1, verbose_name='字典状态(1正常，0停用)')),
                ('create_by', models.CharField(default='', max_length=50, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_by', models.CharField(default='', max_length=50, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'db_table': 's_dict_type',
            },
        ),
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(default='', max_length=32, null=True)),
                ('name', models.CharField(default='', max_length=32, null=True)),
                ('type', models.CharField(default='', max_length=32, null=True)),
                ('content', models.CharField(default='', max_length=255, null=True)),
                ('ip', models.CharField(default='', max_length=32, null=True)),
                ('desc', models.CharField(default='', max_length=255, null=True, verbose_name='描述')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('append_time', models.DateTimeField(auto_now=True, max_length=100, null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 's_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序号')),
                ('caption', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='图标')),
                ('url', models.CharField(blank=True, max_length=128, null=True, verbose_name='请求路由')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='父节点id')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('display', models.IntegerField(blank=True, null=True, verbose_name='显隐')),
            ],
            options={
                'db_table': 's_menus',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='角色名')),
                ('abbreviation', models.CharField(blank=True, max_length=32, null=True, verbose_name='缩写')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序号')),
            ],
            options={
                'db_table': 's_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='admin', max_length=30, unique=True)),
                ('county', models.CharField(default='', max_length=30, verbose_name='区县')),
                ('role', models.IntegerField(default=2, verbose_name='角色')),
                ('description', models.TextField(verbose_name='个人描述')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 's_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
