# Generated by Django 4.2.16 on 2025-07-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultivariateTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(default='', max_length=255, verbose_name='任务名称')),
                ('task_type', models.CharField(default='', max_length=255, verbose_name='任务类型')),
                ('task_status', models.IntegerField(default=1, verbose_name='任务状态')),
                ('count', models.IntegerField(default=0, verbose_name='任务数量')),
                ('flight', models.CharField(default='', max_length=255, verbose_name='飞行棋')),
                ('flight_type', models.CharField(default='', max_length=10, verbose_name='飞行棋类型')),
                ('collect_time', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('collect_type', models.CharField(default='', max_length=100, verbose_name='采集方式')),
                ('tiff_name', models.CharField(default='', max_length=100, verbose_name='航片文件名')),
                ('tiff_service_collection', models.CharField(default='', max_length=100, verbose_name='航片服务集合名')),
                ('tiff_center', models.CharField(default='', max_length=100, verbose_name='航片中心点')),
                ('county', models.CharField(default='', max_length=100, verbose_name='县区')),
                ('tiff_service_url', models.CharField(default='', max_length=100, verbose_name='航片服务url')),
                ('tiff_size', models.IntegerField(default=0, verbose_name='航片大小')),
                ('tiff_resolution', models.IntegerField(default=0, verbose_name='航片分辨率')),
                ('create_person', models.CharField(default='', max_length=100, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.nest', verbose_name='机巢')),
            ],
            options={
                'verbose_name': '多元数据表',
                'verbose_name_plural': '多元数据表',
                'db_table': 's_multivariate_task',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MultivariateData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_name', models.CharField(default='', max_length=255, verbose_name='数据名称')),
                ('file_id', models.CharField(default='', max_length=100, verbose_name='文件ID')),
                ('latitude', models.FloatField(default=0, verbose_name='纬度')),
                ('longitude', models.FloatField(default=0, verbose_name='经度')),
                ('path', models.CharField(default='', max_length=100, verbose_name='路径')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('collect_time', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('bounds', models.CharField(default='', max_length=255, verbose_name='边界')),
                ('task_type', models.CharField(default='', max_length=10, verbose_name='任务类型')),
                ('county', models.CharField(default='', max_length=100, verbose_name='县区')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_person', models.CharField(default='', max_length=100, verbose_name='创建人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.multivariatetask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '多元数据单表',
                'verbose_name_plural': '多元数据单表',
                'db_table': 's_multivariate_data',
                'ordering': ['-create_time'],
            },
        ),
    ]
