# Generated by Django 4.2.16 on 2025-07-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_multivariatetask_multivariatedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multivariatetask',
            name='nest',
        ),
        migrations.DeleteModel(
            name='MultivariateData',
        ),
        migrations.DeleteModel(
            name='MultivariateTask',
        ),
    ]
