# Generated by Django 3.2 on 2026-07-07 10:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_multivariatetask_nest_delete_multivariatedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(default='', max_length=50, verbose_name='行政区划名称')),
                ('region_level', models.IntegerField(default=0, verbose_name='行政区划级别')),
                ('region_code', models.CharField(default='', max_length=50, verbose_name='行政区划代码')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父级id')),
                ('parent_name', models.CharField(default='', max_length=50, verbose_name='父级名称')),
                ('parent_code', models.CharField(default='', max_length=50, verbose_name='父级代码')),
                ('longitude', models.FloatField(default=0, verbose_name='经度')),
                ('latitude', models.FloatField(default=0, verbose_name='纬度')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 't_region',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(default='', max_length=30, verbose_name='所属行政区'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='nest',
            table='t_nest',
        ),
        migrations.AlterModelTable(
            name='rolemenu',
            table='t_role_menu',
        ),
        migrations.AlterModelTable(
            name='sysdictdata',
            table='t_dict_data',
        ),
        migrations.AlterModelTable(
            name='sysdicttype',
            table='t_dict_type',
        ),
        migrations.AlterModelTable(
            name='syslog',
            table='t_log',
        ),
        migrations.AlterModelTable(
            name='sysmenu',
            table='t_menus',
        ),
        migrations.AlterModelTable(
            name='sysrole',
            table='t_role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='t_user',
        ),
    ]
