# Generated by Django 4.2.16 on 2025-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='buffer_distance',
            field=models.CharField(default='', max_length=10, verbose_name=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_show',
            field=models.IntegerField(default=1, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_show_on_panorama',
            field=models.IntegerField(default=1, verbose_name='是否显示全景图'),
        ),
    ]
