# Generated by Django 4.2.16 on 2025-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0002_resource_buffer_distance_resource_is_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='batch_type',
            field=models.IntegerField(default=0, help_text='0:固定批次 1:临时批次', verbose_name='批次类型'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
