# Generated by Django 4.2.16 on 2025-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0003_uploadbatch_batch_type_uploadbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygondata',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='图斑名称'),
        ),
    ]
