# Generated by Django 4.2.16 on 2025-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0004_alter_polygondata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygondata',
            name='unit_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='权属单位名称'),
        ),
    ]
