# Generated by Django 4.2.16 on 2025-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0005_alter_polygondata_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygontask',
            name='create_person',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='创建人'),
        ),
    ]
