# Generated by Django 4.2.18 on 2025-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0006_polygontask_create_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='gis_service_type',
            field=models.CharField(default='1', help_text='1:iServer,2:ArcGIS,3:天地图,4:geoserver', max_length=10, verbose_name='GIS服务类型'),
        ),
    ]
