# Generated by Django 3.2.24 on 2026-06-18 17:28
# Adjusted: skip creating tables that already exist in legacy databases.

import datetime

from django.db import migrations, models
import django.db.models.deletion


def add_panorama_image_columns_if_missing(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    statements = [
        "ALTER TABLE t_panorama_image ADD COLUMN IF NOT EXISTS cube_resolution integer DEFAULT 4576",
        'ALTER TABLE t_panorama_image ADD COLUMN IF NOT EXISTS "desc" text DEFAULT \'\'',
        "ALTER TABLE t_panorama_image ADD COLUMN IF NOT EXISTS max_level integer DEFAULT 5",
        "ALTER TABLE t_panorama_image ADD COLUMN IF NOT EXISTS tile_resolution integer DEFAULT 512",
    ]
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def add_plotrecord_clue_column_if_missing(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE t_plot_record ADD COLUMN IF NOT EXISTS clue_id integer"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0007_resource_gis_service_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='FlyOrder',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('order_name', models.CharField(default='', max_length=100, verbose_name='订单名称')),
                        ('data_type', models.CharField(default='', max_length=100, verbose_name='数据类型')),
                        ('organization', models.CharField(default='', max_length=255, verbose_name='所属单位')),
                        ('collect_type', models.CharField(default='', max_length=100, verbose_name='采集方式')),
                        ('create_person', models.CharField(default='', max_length=100, verbose_name='创建人')),
                        ('status', models.IntegerField(default=0, verbose_name='订单状态')),
                        ('county', models.CharField(default='', max_length=100, verbose_name='县区')),
                        ('collect_time', models.DateField(default=datetime.datetime(2026, 6, 18, 17, 28, 48, 738805), verbose_name='采集时间')),
                        ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panorama.route', verbose_name='关联航线')),
                    ],
                    options={
                        'verbose_name': '订单表',
                        'verbose_name_plural': '订单表',
                        'db_table': 't_fly_order',
                        'ordering': ['-create_time'],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PlotRecord',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('color', models.CharField(default='', max_length=50, verbose_name='颜色')),
                        ('transparent', models.CharField(default='', max_length=50, verbose_name='透明度')),
                        ('plot_type', models.CharField(default='', max_length=50, verbose_name='标绘类型')),
                        ('plot_name', models.CharField(default='', max_length=50, verbose_name='名称')),
                        ('plot_status', models.IntegerField(default=0, verbose_name='状态')),
                        ('plot_desc', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='描述')),
                        ('line_color', models.CharField(default='', max_length=50, verbose_name='线颜色')),
                        ('line_width', models.CharField(default='', max_length=50, verbose_name='线宽度')),
                        ('clue_name', models.CharField(default='', max_length=50, verbose_name='线索名称')),
                        ('image_id', models.CharField(default='', max_length=100, verbose_name='图片ID')),
                        ('create_person', models.CharField(default='', max_length=50, verbose_name='创建人')),
                        ('point_name', models.CharField(default='', max_length=50, verbose_name='点位名称')),
                        ('point_id', models.CharField(default='', max_length=50, verbose_name='点位ID')),
                        ('geometry', models.TextField(default='', verbose_name='几何信息')),
                        ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                        ('plot_area', models.FloatField(blank=True, null=True, verbose_name='面积')),
                        ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                    ],
                    options={
                        'db_table': 't_plot_record',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='SupervisionPolygonVertical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('polygon_id', models.IntegerField(default=0, verbose_name='图斑ID')),
                ('vertical_view_id', models.IntegerField(default=0, verbose_name='俯视图ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监管项目图斑表',
                'verbose_name_plural': '监管项目图斑表',
                'db_table': 't_supervision_polygon_vertical',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(default='', max_length=100, verbose_name='数据类型')),
                ('count', models.IntegerField(default=0, verbose_name='监管项目数量')),
                ('create_person', models.CharField(default='', max_length=100, verbose_name='创建人')),
                ('status', models.IntegerField(default=0, verbose_name='订单状态')),
                ('county', models.CharField(default='', max_length=100, verbose_name='县区')),
                ('collect_time', models.DateField(default=datetime.datetime(2026, 6, 18, 17, 28, 48, 738805), verbose_name='采集时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '监管项目表',
                'verbose_name_plural': '监管项目表',
                'db_table': 't_supervision_project',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionProjectPolygon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supervision_project_id', models.IntegerField(verbose_name='监管项目')),
                ('polygon', models.TextField(default='', verbose_name='图斑')),
                ('latitude', models.FloatField(default=0, verbose_name='纬度')),
                ('longitude', models.FloatField(default=0, verbose_name='经度')),
                ('polygon_type', models.CharField(default='3', max_length=100, verbose_name='图斑类型')),
                ('construction_desc', models.TextField(default='', verbose_name='建设描述')),
                ('color_desc', models.TextField(default='', verbose_name='颜色描述')),
                ('point_id', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='关联全景点')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('is_del', models.IntegerField(default=0, verbose_name='是否删除')),
                ('create_person', models.CharField(default='', max_length=100, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监管项目图斑表',
                'verbose_name_plural': '监管项目图斑表',
                'db_table': 't_supervision_project_polygon',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionProjectRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supervision_project_id', models.IntegerField(verbose_name='监管项目')),
                ('route_id', models.IntegerField(verbose_name='航线')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '监管项目航线关联表',
                'verbose_name_plural': '监管项目航线关联表',
                'db_table': 't_supervision_project_route',
                'ordering': ['-create_time'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Region',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='panoramaimage',
                    name='cube_resolution',
                    field=models.IntegerField(default=4576, verbose_name='立方体贴图分辨率'),
                ),
                migrations.AddField(
                    model_name='panoramaimage',
                    name='desc',
                    field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
                ),
                migrations.AddField(
                    model_name='panoramaimage',
                    name='max_level',
                    field=models.IntegerField(default=5, verbose_name='最大层级'),
                ),
                migrations.AddField(
                    model_name='panoramaimage',
                    name='tile_resolution',
                    field=models.IntegerField(default=512, verbose_name='瓦片分辨率'),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_panorama_image_columns_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='clue',
                    name='position',
                    field=models.TextField(default='', verbose_name='方框的位置'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='plotrecord',
                    name='clue',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panorama.clue', verbose_name='线索'),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_plotrecord_clue_column_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
