# Generated by Django 6.0.6 on 2026-06-24 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0008_auto_20260618_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='polygon_color',
            field=models.CharField(default='#fff', max_length=255, null=True, verbose_name='图斑颜色'),
        ),
        migrations.AddField(
            model_name='resource',
            name='polygon_opacity',
            field=models.FloatField(blank=True, default=0.8, null=True, verbose_name='图斑透明度'),
        ),
        migrations.AddField(
            model_name='resource',
            name='polygon_weight',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='图斑宽度'),
        ),
        migrations.AlterField(
            model_name='flyorder',
            name='collect_time',
            field=models.DateField(default=datetime.datetime(2026, 6, 24, 11, 38, 55, 281709), verbose_name='采集时间'),
        ),
        migrations.AlterField(
            model_name='supervisionproject',
            name='collect_time',
            field=models.DateField(default=datetime.datetime(2026, 6, 24, 11, 38, 55, 281709), verbose_name='采集时间'),
        ),
        migrations.AlterField(
            model_name='supervisionproject',
            name='count',
            field=models.IntegerField(default='', verbose_name='监管项目数量'),
        ),
    ]
