# Generated by Django 3.2 on 2026-07-07 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0009_resource_polygon_color_resource_polygon_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyorder',
            name='collect_time',
            field=models.DateField(default=datetime.datetime(2026, 7, 7, 10, 41, 11, 752459), verbose_name='采集时间'),
        ),
        migrations.AlterField(
            model_name='supervisionproject',
            name='collect_time',
            field=models.DateField(default=datetime.datetime(2026, 7, 7, 10, 41, 11, 752574), verbose_name='采集时间'),
        ),
    ]
