# Generated by Django 4.2.16 on 2025-07-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='模型编号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='模型名称')),
                ('epoch', models.IntegerField(verbose_name='迭代次数')),
                ('thumbnail', models.ImageField(default='', upload_to='thumbnail/', verbose_name='缩略图')),
                ('framework', models.CharField(max_length=50, verbose_name='模型框架')),
                ('network', models.CharField(default='', max_length=50, verbose_name='网络')),
                ('learning_rate', models.FloatField(verbose_name='学习率')),
                ('country', models.CharField(default='', max_length=50, verbose_name='样本区域')),
                ('datasets_count', models.IntegerField(default=0, verbose_name='样本数量')),
                ('datasets_size', models.CharField(default='256x256', max_length=50, null=True, verbose_name='样本大小')),
                ('model_path', models.CharField(default='', max_length=500, verbose_name='模型路径')),
                ('status', models.BooleanField(default=True, help_text='0 废弃，1 使用', verbose_name='模型状态')),
                ('industry', models.CharField(default='', max_length=50, verbose_name='行业')),
                ('scene', models.CharField(default='', max_length=50, verbose_name='场景')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('note', models.TextField(null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'db_table': 'm_models',
            },
        ),
    ]
