# Generated by Django 3.2 on 2026-07-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='标签代码')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('is_del', models.IntegerField(default=1, verbose_name='是否可用')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('create_person', models.CharField(default='', max_length=100, verbose_name='创建用户')),
                ('color', models.CharField(default='#FF0000', max_length=7, verbose_name='显示颜色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '检测标签',
                'verbose_name_plural': '检测标签',
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='ModelScene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, verbose_name='模型场景')),
                ('is_del', models.IntegerField(default=1, verbose_name='是否可用')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('create_person', models.CharField(default='', max_length=100, verbose_name='创建用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模型场景表',
                'verbose_name_plural': '模型场景表',
                'db_table': 't_model_scene',
            },
        ),
        migrations.RemoveField(
            model_name='models',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='models',
            name='scene',
        ),
        migrations.AddField(
            model_name='models',
            name='create_person',
            field=models.CharField(default='', max_length=100, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='models',
            name='is_del',
            field=models.IntegerField(default=1, verbose_name='是否可用'),
        ),
        migrations.AddField(
            model_name='models',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='models',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='模型编号'),
        ),
        migrations.AlterModelTable(
            name='models',
            table='t_models',
        ),
        migrations.CreateModel(
            name='ModelSceneLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100, verbose_name='标签')),
                ('is_del', models.IntegerField(default=1, verbose_name='是否可用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.category', verbose_name='模型能力')),
                ('model_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.modelscene', verbose_name='模型场景')),
            ],
            options={
                'verbose_name': '场景标签配置',
                'verbose_name_plural': '场景标签配置',
                'db_table': 't_model_scene_label',
            },
        ),
        migrations.AddField(
            model_name='modelscene',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.models', verbose_name='检测模型'),
        ),
        migrations.CreateModel(
            name='ModelLabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签ID')),
                ('category_name', models.CharField(default='', max_length=100, verbose_name='标签名称')),
                ('is_del', models.IntegerField(default=1, verbose_name='是否可用')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.category', verbose_name='检测标签')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.models', verbose_name='检测模型')),
            ],
            options={
                'verbose_name': '模型能力',
                'verbose_name_plural': '模型能力',
                'db_table': 't_model_label',
            },
        ),
    ]
