[aliyun]
alibaba_cloud_access_key_id = YOUR_ALIBABA_CLOUD_ACCESS_KEY_ID
alibaba_cloud_access_key_secret = YOUR_ALIBABA_CLOUD_ACCESS_KEY_SECRET
endpoint =https://oss-cn-hangzhou.aliyuncs.com
region =cn-hangzhou
bucket_name=supermap-dk

[common]
is_change_detection = 0
cut_image_way = 2
host = 127.0.0.1
port = 8009

[database]
database_host = 127.0.0.1
database_port = 5432
database_name = gtus
database_user = postgres
database_password = 123456

[screenshot]
screenshot_url = http://192.168.60.6:10086

# 推送地址
[push_address]
push_host = 192.168.2.191
push_port = 9910

#目标检测地址
[object_detection]
od_url = http://127.0.0.1:5561/detection_web

[redis]
broker_url = redis://127.0.0.1:6379/14
celery_result_backend = redis://127.0.0.1:6379/15
celery_app2_broker_url = redis://127.0.0.1:6379/12
celery_app2_celery_result_backend = redis://127.0.0.1:6379/13
ai_db = 12

[other]
agent_url = http://2.24.4.68:28080/apis/ais-v2/chat/completions
nona_exe_path = D:\\Program Files\\Hugin\\bin\\nona.exe

[ai_interpretation]
batch_size = 4
block_size = 256
pool_num = 1
clip_size = 20000
max_single_img_size = 40000
area_of_figure_above = 0.3
overlap_x = 10
overlap_y = 10
max_savenum = 230000
dataSize = 50000
ip_address = 192.168.60.81
redis_ip = 192.168.50.42
# 分幅阈值，行*列/分辨率
oversize = 40000
# 分幅最小行列长宽（单位：张，每张大小：256*256）
split_unit= 80
# 缩略图最短边长度
squeeze_unit= 400
#多分类配置
num_classes = 7
st_colormap= [[0,0,0], [255,1,1], [255,2,2],[255,3,3],[255,4,4],[255,5,5],[255,6,6]]
st_classes = ['unchanged', 'water', 'road', 'building','cultivated land', 'forest','others']
st_colormap_pixel= [0, 1, 2, 3, 4, 5,6]
share_path = /home/yhj/LAIS-AI/img_data
data_path = /home/yhj/LAIS-AI/img_data/remote_images


