# Generated by Django 4.2.16 on 2025-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationTaskResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, verbose_name='任务名')),
                ('path_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='影像分割服务ID')),
                ('prev_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='前序任务ID')),
                ('next_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='后续任务ID')),
                ('data_path_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='数据路径ID')),
                ('task_type', models.CharField(default='', max_length=255, verbose_name='任务类型')),
                ('county', models.CharField(default='', max_length=255, verbose_name='区县')),
                ('create_person', models.CharField(default='', max_length=100, verbose_name='创建用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 't_interpretation_task_result',
            },
        ),
    ]
