# Generated by Django 3.2 on 2026-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, verbose_name='任务名')),
                ('model_name', models.CharField(default='', max_length=255, verbose_name='模型名')),
                ('model_path', models.CharField(default='', max_length=255, verbose_name='模型路径')),
                ('model_network', models.CharField(default='', max_length=255, verbose_name='模型网络')),
                ('fragment', models.CharField(default='', max_length=255, verbose_name='碎片化')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('config_path', models.CharField(default='', max_length=255, verbose_name='配置文件路径')),
                ('input_path', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='输入路径')),
                ('input_path_prev', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='前景输入路径')),
                ('input_path_next', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='后景输入路径')),
                ('output_path', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='输出路径')),
                ('building_regular', models.IntegerField(default=0, verbose_name='建筑物规则化')),
                ('create_person', models.CharField(default='', max_length=100, verbose_name='创建用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_type', models.CharField(default='', max_length=255, verbose_name='任务类型')),
                ('detection_type', models.CharField(default='', max_length=255, verbose_name='检测类型')),
                ('county', models.CharField(default='', max_length=255, verbose_name='区县')),
            ],
            options={
                'db_table': 't_interpretation_task',
            },
        ),
    ]
