# Generated by Django 4.2.16 on 2025-07-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='multivariatedata',
            table='t_multivariate_data',
        ),
        migrations.AlterModelTable(
            name='multivariatetask',
            table='t_multivariate_task',
        ),
    ]
