# Generated by Django 4.2.16 on 2025-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_multivariatedata_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivariatetask',
            name='organization',
            field=models.CharField(default='', max_length=255, verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='multivariatetask',
            name='flight',
            field=models.CharField(default='', max_length=255, verbose_name='飞行器'),
        ),
        migrations.AlterField(
            model_name='multivariatetask',
            name='flight_type',
            field=models.CharField(default='', max_length=10, verbose_name='飞行器类型'),
        ),
    ]
