# Generated by Django 4.2.16 on 2025-07-21 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panorama', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='报告编号')),
                ('count', models.IntegerField(default=0, verbose_name='报告数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_report', to='panorama.batch', verbose_name='所属批次')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panorama.scene', verbose_name='关联场景')),
            ],
            options={
                'db_table': 't_batch_report',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='报告编号')),
                ('report_name', models.CharField(default='', max_length=100, verbose_name='报告名称')),
                ('village', models.CharField(default='', max_length=100, null=True, verbose_name='关联村')),
                ('file_id', models.CharField(default='', max_length=50, verbose_name='文件地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('batch_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.batchreport', verbose_name='所属批次报告')),
            ],
            options={
                'db_table': 't_report',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('download_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='下载编号')),
                ('count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='下载时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改时间')),
                ('downloader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下载用户')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.report', verbose_name='所属报告')),
            ],
            options={
                'db_table': 't_download',
            },
        ),
    ]
